### ISSUE TITLE
Implement EdDSA

### ISSUE THREAD

**Issue by arianvp** [arianvp/haskell-fido2#20]
I think my employer will probably want to avoid EC256 if possible. EdDSA seems easier to implement though; as the signature format isn't legacy but COSE  (though this is underspecified in the spec currently. See https://github.com/w3c/webauthn/issues/1441)

**Comment by selfissued** [comment]
Note that 25519 has been in the IANA Cose Algorithms Registry https://www.iana.org/assignments/cose/cose.xhtml since July 2017, since it was defined by RFC 8152.

**Comment by arianvp** [comment]
I'm aware that it's part of COSE!  It's just not clear from the webauthn spec that everything that is supported in COSE is supported in webauthn.  Especially, the signature format for assertions is not the same as in COSE for at least `ES256` and `RS256` and for others it's underspecified.

**Comment by arianvp** [comment]
Other thing I worry about is how well it is supported.  I know Yubikey and Nitrokey both support it; but does Microsoft Hello / TPMs support it as well? 
Is it documented what algorithms Windows 10 implements? 

Of course we can always fall back to EC256 if needed.

**Comment by arianvp** [comment]
Fixed by #23
